Courier Management System/Models/JobViewModels.cs
using System;
using System.Collections.Generic;

namespace Courier_Management_System.Models
{
    public class JobLocationViewModel
    {
        public string OrderId
        {
            get; set;
        }

        public string CustomerName
        {
            get; set;
        }

        public string CustomerAddress
        {
            get; set;
        }

        public string CustomerMobilePhone
        {
            get; set;
        }

        public string CustomerCompany
        {
            get; set;
        }

        public List<string> ConsignmentNumbers
        {
            get; set;
        }

        public int Type
        {
            get; set;
        }

        public bool IsDone
        {
            get; set;
        }

        public string SizeName
        {
            get; set;
        }

        public List<Order> Orders
        {
            get; set;
        }
    }

    public class RouteStepViewModel
    {
        public double Latitude
        {
            get; set;
        }

        public double Longitude
        {
            get; set;
        }
    }

    public class JobRouteViewModel
    {
        public int Stops
        {
            get; set;
        }

        public decimal NetProfit
        {
            get; set;
        }

        public List<int> Steps
        {
            get; set;
        }

        public List<double> Distances
        {
            get; set;
        }

        public List<double> Loads
        {
            get; set;
        }

        public List<decimal> Profits
        {
            get; set;
        }

        public List<double> DrivingTimes
        {
            get; set;
        }

        public List<double> Arrivals
        {
            get; set;
        }

        public List<double> Departures
        {
            get; set;
        }

        public List<double> WorkingTimes
        {
            get; set;
        }

        public string Path
        {
            get; set;
        }

        public List<RouteStepViewModel> FootSteps
        {
            get; set;
        }
    }

    public class JobViewModel
    {
        public List<JobLocationViewModel> Locations
        {
            get; set;
        }

        public JobRouteViewModel Route
        {
            get; set;
        }
    }

    public class JobReportViewModel
    {
        public long Id
        {
            get; set;
        }

        public int VehicleId
        {
            get; set;
        }

        public string VehicleNumber
        {
            get; set;
        }

        public JobViewModel Routes
        {
            get; set;
        }

        public DateTime? TakenOn
        {
            get; set;
        }

        public string TakenBy
        {
            get; set;
        }

        public int TotalPickups
        {
            get; set;
        }

        public int TotalDeliveries
        {
            get; set;
        }

        public double TotalDistances
        {
            get; set;
        }

        public double TotalDrivingTime
        {
            get; set;
        }

        public double TotalWorkingTime
        {
            get; set;
        }

        public DateTime CreatedOn
        {
            get; set;
        }
    }

    public class JobHistorySummaryViewModel
    {
        public DateTime? FromDate { get; set; }

        public DateTime? ToDate { get; set; }

        public bool IsPickup { get; set; }
    }
}

Courier Management System/Controllers/Api/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using Courier_Management_System.Helpers;
using Courier_Management_System.Models;
using Courier_Management_System.Services;
using Courier_Management_System.Services.Implement;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;

namespace Courier_Management_System.Controllers.Api
{
    [Authorize]
    [RoutePrefix("api/jobs")]
    public class JobsController : ApiController
    {
        #region Private

        private CourierDBEntities db = new CourierDBEntities();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public JobsController()
        {
            db.Database.CommandTimeout = 600;
        }

        public JobsController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.Current.GetOwinContext().Get<ApplicationSignInManager>(); }
            private set { _signInManager = value; }
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        #endregion

        [Route("list")]
        [HttpPost]
        public async Task<IHttpActionResult> List()
        {
            // Get driver's information of this account
            IList<string> roles = new List<string>();
            try
            {
                roles = await UserManager.GetRolesAsync(User.Identity.GetUserId());
            }
            catch (Exception exc)
            {
                // No roles
                return NotFound();
            }

            var profiles = await AccountHelper.Profile(User.Identity.GetUserName(), roles);

            var driverId = 0;
            var driverType = AccountTypes.Staff;
            foreach (var profile in profiles)
            {
                if (profile.Profile.IsDriver == true)
                {
                    driverId = profile.Profile.Id;
                    driverType = profile.ProfileType == AccountHelper.StaffDriverRole
                                     ? AccountTypes.Staff
                                     : AccountTypes.Contractor;
                    break;
                }
            }

            if (driverId == 0)
            {
                return NotFound();
            }

            try
            {
                var startDate = DateTime.Now.Date;
                var endDate = startDate.AddDays(1);
                var list = (from job in db.Jobs
                            from vehicle in db.Vehicles
                            where !job.IsDeleted && !job.IsSpecial &&
                                  //job.TakenOn >= startDate && job.TakenOn < endDate && 
                                  !job.CompletedOn.HasValue && job.DriverId == driverId &&
                                  job.DriverType == (int)driverType && vehicle.Id == job.VehicleId
                            select new
                            {
                                job.Id,
                                job.VehicleId,
                                vehicle.VehicleNumber,
                                job.Routes,
                                job.TakenOn,
                                job.TakenBy,
                                job.TotalPickups,
                                job.TotalDeliveries,
                                job.TotalDistances,
                                job.TotalDrivingTime,
                                job.TotalWorkingTime,
                                job.CreatedOn
                            }).ToList();
                var jobs = new List<dynamic>();
                foreach (var item in list)
                {
                    var route = JsonConvert.DeserializeObject<JobViewModel>(item.Routes);

                    // Get order list
                    var orderIds = route.Locations.Where(x => !string.IsNullOrEmpty(x.OrderId)).Select(x => x.OrderId).Distinct().ToList();
                    var ids = new List<long>();
                    foreach (var orderId in orderIds)
                    {
                        ids.AddRange(orderId.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(i => long.Parse(i)));
                    }

                    ids = ids.Distinct().ToList();
                    var orders = db.Orders.Where(x => !x.IsDeleted && ids.Contains(x.Id))
                                   .Select(
                                           x => new
                                           {
                                               x.Id,
                                               x.FromName,
                                               x.FromAddress,
                                               x.FromMobilePhone,
                                               x.Customer.CustomerCompany,
                                               x.ToName,
                                               x.ToAddress,
                                               x.ToMobilePhone,
                                               x.ConsignmentNumber,
                                               x.Status,
                                               x.Size.SizeName,
                                               x.PickupTimeSlotId,
                                               x.DeliveryTimeSlotId,
                                               x.CreatedOn,
                                               x.ConfirmedOn,
                                               x.OperatorRemark,
                                               CodOptionOfOrders = x.CodOptionOfOrders
                                                                         .Where(i => !i.IsDeleted)
                                                                         .Select(
                                                                                 i => new
                                                                                 {
                                                                                     i.Amount,
                                                                                     CodOptionType = i.CodOption.Type,
                                                                                     CodOptionDescription = i.CodOption.Description
                                                                                 })
                                                                         .ToList(),
                                               x.IsExchange,
                                               ExtraRequests = x.ExtraRequests
                                                                     .Where(i => !i.IsDeleted)
                                                                     .OrderByDescending(i => i.CreatedOn)
                                                                     .Select(
                                                                             i => new
                                                                             {
                                                                                 RequestContent = i.RequestContent,
                                                                                 RequestType = i.RequestType
                                                                             })
                                                                     .ToList(),
                                           })
                                   .ToList();

                    foreach (var location in route.Locations)
                    {
                        var oids = (string.IsNullOrEmpty(location.OrderId) ? "" : location.OrderId).Split(
                                                                                                          new char[] { ',' },
                                                                                                          StringSplitOptions.RemoveEmptyEntries);
                        var tempOrders = orders.Where(x => oids.Contains(x.Id.ToString())).ToList();
                        location.ConsignmentNumbers = tempOrders.Select(x => x.ConsignmentNumber).ToList();
                        if (tempOrders.Count > 0)
                        {
                            if (location.Type == 0)
                            {
                                // Pickup
                                location.CustomerName = tempOrders.FirstOrDefault().FromName;
                                location.CustomerAddress = tempOrders.FirstOrDefault().FromAddress;
                                location.CustomerMobilePhone = tempOrders.FirstOrDefault().FromMobilePhone;
                                location.CustomerCompany = tempOrders.FirstOrDefault().CustomerCompany;
                                location.IsDone = tempOrders.All(x => x.Status != (int)OrderStatuses.ItemHasBeingPicked);
                                location.SizeName = tempOrders.FirstOrDefault().SizeName;
                            }
                            else
                            {
                                // Delivery
                                location.CustomerName = tempOrders.FirstOrDefault().ToName;
                                location.CustomerAddress = tempOrders.FirstOrDefault().ToAddress;
                                location.CustomerMobilePhone = tempOrders.FirstOrDefault().ToMobilePhone;

Courier Management System/Areas/Admin/Views/Jobs/History.cshtml
@using Courier_Management_System.Helpers
@{
    ViewBag.Title = "Show History Jobs";
}

@section scripts
{
    <script>
        $(function () {
            $('#menu-show-history-jobs').addClass("active");
            $('#menu-show-history-jobs').parents('.treeview').addClass("active");
            $('#menu-show-history-jobs').parents('.treeview').find('.treeview-menu').addClass("menu-open").css("display", "block");
        });

        function showOrderDetail(cn) {
            popupControl.SetContentUrl("@Url.Action("OrderDetail", "Jobs")" + "?consignmentNumber=" + cn);
            popupControl.Show();
        }
    </script>
}

<section class="content">
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <input type="hidden" name="SearchOrderText" id="SearchOrderText" />
            @Html.Action("HistoryListViewPartial")
        </div>
    </div>
</section>

@Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "popupControl";
    settings.CloseAction = CloseAction.OuterMouseClick;
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    settings.AllowDragging = true;
    settings.AllowResize = true;
    settings.Modal = true;
    settings.EnableHotTrack = true;
    settings.Width = 600;
    settings.Height = 500;
    settings.HeaderText = "Order detail";

}).GetHtml()

Courier Management System/Areas/Admin/Views/Jobs/List.cshtml
@using System.Web.UI.WebControls
@using Courier_Management_System.Helpers
@{
    ViewBag.Title = "Show Today Jobs";
}

@section scripts
{
    <script>
        $(function() {
            $('#menu-show-today-jobs').addClass("active");
            $('#menu-show-today-jobs').parents('.treeview').addClass("active");
            $('#menu-show-today-jobs').parents('.treeview').find('.treeview-menu').addClass("menu-open").css("display", "block");
        });

        function deleteRow(index) {
            swal(
                {
                    title: "Are you sure?",
                    text: "You will not be able to recover this action!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: true
                },
                function() {
                    gridViewJobs.DeleteRow(index);
                });
        }

        function showOrderDetail(cn) {
            popupControl.SetContentUrl("@Url.Action("OrderDetail", "Jobs")" + "?consignmentNumber=" + cn);
            popupControl.Show();
        }

        function showOrderList(id) {
            popupControl.SetWidth($(window).innerWidth() * 0.8);
            popupControl.SetHeight($(window).innerHeight() * 0.8);
            popupControl.SetContentUrl("@Url.Action("OrdersList", "Jobs")" + "/" + id);
            popupControl.Show();
        }
    </script>
}

<section class="content">
    <form method="POST" action="@Url.Action("Import", "Jobs")" enctype="multipart/form-data">

        <div class="row">
            <div class="col-md-12 col-sm-12 margin-bottom">
                @if (User.IsInRole(AccountHelper.AdministratorRole) || User.IsInRole(AccountHelper.DispatchImportJobs))
                {
                    <input type="file" name="importFile" style="display: inline-block;" />
                    <button class="btn btn-primary">Import</button>
                }
                <a class="btn btn-info" href="@(SettingProvider.VrpLink.TrimEnd('/') + "/Home/History")" target="_blank">Display Plan</a>
                @if (User.IsInRole(AccountHelper.AdministratorRole) || User.IsInRole(AccountHelper.DispatchPrintPlan))
                {
                    @*<a class="btn btn-warning" href="@Url.Action("PrintPlan", "Jobs")" target="_blank">Print Driver Report</a>*@
                    <div class="dropdown pull-right">
                        <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            Print Driver Report
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="@Url.Action("PrintPlan", "Jobs")">Default</a></li>
                            <li><a href="@Url.Action("PrintPlan", "Jobs",new {sortType = 1})">Ascending by Postal code</a></li>
                            <li><a href="@Url.Action("PrintPlan", "Jobs",new {sortType = 2})">Descending by Postal code</a></li>
                        </ul>
                    </div>
                }
            </div>
        </div>

        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger alert-dismissible">
                @Html.Raw(ViewBag.ErrorMessage)
            </div>
        }

        <div class="row">
            <div class="col-lg-12 col-xs-12">
                @Html.Action("ListViewPartial")
            </div>
        </div>

    </form>

</section>

@Html.DevExpress().PopupControl(settings =>
                                {
                                    settings.Name = "popupControl";
                                    settings.CloseAction = CloseAction.OuterMouseClick;
                                    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
                                    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
                                    settings.AllowDragging = true;
                                    settings.AllowResize = true;
                                    settings.Modal = true;
                                    settings.EnableHotTrack = true;
                                    settings.Width = 600;
                                    settings.Height = 400;
                                    settings.HeaderText = "Orders";
                                }).GetHtml()

Courier Management System/Areas/Admin/Views/Jobs/PrintSpecialPlan.cshtml
@using Courier_Management_System.Models

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";
    ViewBag.Title = "Print Plan";
    var jobs = (ViewBag.Jobs as List<DriverReportViewModel> ?? new List<DriverReportViewModel>())
        .GroupBy(x => new
                      {
                          x.Name,
                          x.UserName,
                          TakenOn = x.TakenOn?.ToString("dd MMM yyyy")
                      })
        .OrderBy(x => x.Key.TakenOn).ThenBy(x => x.Key.Name)
        .ToList();
}

@foreach (var group in jobs)
{
    var idx = 0;
    <table id="reportList" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th colspan="3">Driver (User name):</th>
                <th colspan="4">@group.Key.Name (@group.Key.UserName)</th>
                <th>Date:</th>
                <th colspan="6">@(group.Key.TakenOn)</th>
            </tr>
            <tr>
                <th style="width: 5%">#</th>
                <th colspan="2" style="width: 10%">FROM COMPANY NAME</th>
                <th style="width: 10%">FROM NAME</th>
                <th colspan="2" style="width: 15%">FROM ADDRESS</th>
                <th style="width: 7%">Postal Code</th>
                <th style="width: 10%">TO NAME</th>
                <th style="width: 10%">TO PHONE</th>
                <th style="width: 15%">TO ADDRESS</th>
                <th style="width: 7%">Postal Code</th>
                <th style="width: 5%">Type</th>
                <th style="width: 6%">Consignment Number</th>
                <th style="width: 15%">Signature</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in group.SelectMany(x => x.Orders).OrderBy(x => x.ToZipCode))
            {
                ++idx;
                <tr>
                    <td>@(idx)</td>
                    <td colspan="2">@order.Customer.CustomerName</td>
                    <td>@order.FromName</td>
                    <td colspan="2">@order.FromAddress</td>
                    <td>@order.FromZipCode</td>
                    <td>@order.ToName</td>
                    <td>@order.ToMobilePhone</td>
                    <td>@order.ToAddress</td>
                    <td>@order.ToZipCode</td>
                    <td>@order.ProductType.ProductTypeName</td>
                    <td>@order.ConsignmentNumber</td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>

    <hr />
    <p style="page-break-after: always"></p>
}

Courier Management System/Areas/Admin/Views/Jobs/Special.cshtml
@using System.Web.UI.WebControls
@using Courier_Management_System.Helpers
@{
    ViewBag.Title = "Show Special Jobs";
}

@section scripts
{
    <script>
        var selectedJobsToDelete = [];

        $(function () {
            $('#menu-show-special-jobs').addClass("active");
            $('#menu-show-special-jobs').parents('.treeview').addClass("active");
            $('#menu-show-special-jobs').parents('.treeview').find('.treeview-menu').addClass("menu-open").css("display", "block");
        });

        function deleteRow(index) {
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this action!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: true
            }, function () {
                gridViewJobs.DeleteRow(index);
            });
        }

        function showOrderDetail(cn) {
            popupControl.SetContentUrl("@Url.Action("OrderDetail", "Jobs")" + "?consignmentNumber=" + cn);
            popupControl.Show();
        }

        // Collect sellected rows
        function OnGetSelectedFieldValues(selectedValues) {
            if (selectedValues.length != 0) {
                $('#multiDelete').removeAttr("disabled");
            }
            else {
                $('#multiDelete').attr("disabled", true);
            }
            selectedJobsToDelete = selectedValues;
        }

        function deleteSelectedRow() {
            if (selectedJobsToDelete.length == 0) {
                return;
            }
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this action!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete all selected items!",
                closeOnConfirm: true
            }, function () {
                $('#multiDelete').attr("disabled", true);
                $("#jobsSelected").val(selectedJobsToDelete);
                $('#multiDeleteForm').submit();
            });
        }
    </script>
}

<section class="content">

    <div class="row">
        <div class="col-md-9 col-sm-9 margin-bottom">
            @if (User.IsInRole(AccountHelper.AdministratorRole) || User.IsInRole(AccountHelper.DispatchPrintSpecialPlan))
            {
                <a class="btn btn-warning" href="@Url.Action("PrintSpecialPlan", "Jobs")" target="_blank">Print Driver Report</a>
            }
        </div>
        <div class="col-md-3 col-sm-3 margin-bottom">
            @using (Html.BeginForm("SpecialListViewPartialMultiDelete", "Jobs", FormMethod.Post, new { id = "multiDeleteForm", @class = "" }))
            {

                if (User.IsInRole(AccountHelper.AdministratorRole) || User.IsInRole(AccountHelper.DispatchDeleteJob))
                {
                    <input type="hidden" name="jobsSelected" id="jobsSelected" value="" />
                    <a id="multiDelete" class="btn bg-maroon pull-right" onclick="deleteSelectedRow()" disabled><span class="fa fa-trash-o"></span> Delete selected rows</a>
                }
            }
        </div>
    </div>
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger alert-dismissible">
            @Html.Raw(ViewBag.ErrorMessage)
        </div>
    }

    <div class="row">
        <div class="col-lg-12 col-xs-12" id="test">
            @Html.Action("SpecialListViewPartial")
        </div>
    </div>
</section>

@Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "popupControl";
    settings.CloseAction = CloseAction.OuterMouseClick;
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    settings.AllowDragging = true;
    settings.AllowResize = true;
    settings.Modal = true;
    settings.EnableHotTrack = true;
    settings.Width = 600;
    settings.Height = 500;
    settings.HeaderText = "Order detail";

}).GetHtml()

Courier Management System/Areas/Admin/Views/Jobs/_ContractorDriversComboBox.cshtml
@using System.Web.UI.WebControls
@using Courier_Management_System.Areas.Admin.Controllers
@model Courier_Management_System.Models.DriverReportViewModel

@if (Model != null)
{
    @Html.DevExpress().ComboBox(comboSettings =>
{
    comboSettings.Name = "driverForRow" + Model.Id;
    comboSettings.Width = Unit.Percentage(100);
    comboSettings.Properties.DropDownStyle = DropDownStyle.DropDownList;

    comboSettings.Properties.CallbackPageSize = 30;
    comboSettings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
    comboSettings.Properties.TextField = "Name";
    comboSettings.Properties.TextFormatString = "{0}";
    comboSettings.Properties.ValueField = "Id";
    comboSettings.Properties.ValueType = typeof(string);

    comboSettings.Properties.Columns.Add("AccountType", "Account Type", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("UserName", "UserName", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("Name", "Name", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("MobileNumber", "Mobile Number", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("ICNumber", "IC Number", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("IdentityNumber", "Staff Number", Unit.Pixel(200));

    comboSettings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s, e) { gridViewJobs.PerformCallback({ id: " + Model.Id + ", action: 'assign', driver: s.GetValue() }); }";

}).BindList(DriversController.GetContractors().OrderBy(x => x.AccountType).ToList()).GetHtml()
}

Courier Management System/Areas/Admin/Views/Jobs/_DriversComboBox.cshtml
@using System.Web.UI.WebControls
@using Courier_Management_System.Areas.Admin.Controllers
@model Courier_Management_System.Models.DriverReportViewModel

@if (Model != null)
{
    @Html.DevExpress().ComboBox(comboSettings =>
{
    comboSettings.Name = "driverForRow" + Model.Id;
    comboSettings.Width = Unit.Percentage(100);
    comboSettings.Properties.DropDownStyle = DropDownStyle.DropDownList;

    comboSettings.Properties.CallbackPageSize = 30;
    comboSettings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
    comboSettings.Properties.TextField = "Name";
    comboSettings.Properties.TextFormatString = "{0}";
    comboSettings.Properties.ValueField = "Id";
    comboSettings.Properties.ValueType = typeof(string);

    comboSettings.Properties.Columns.Add("AccountType", "Account Type", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("UserName", "UserName", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("Name", "Name", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("MobileNumber", "Mobile Number", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("ICNumber", "IC Number", Unit.Pixel(200));
    comboSettings.Properties.Columns.Add("IdentityNumber", "Staff Number", Unit.Pixel(200));

    comboSettings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s, e) { gridViewJobs.PerformCallback({ id: " + Model.Id + ", action: 'assign', driver: s.GetValue() }); }";

}).BindList(DriversController.GetDrivers().Where(x => x.IsActive).OrderBy(x => x.AccountType).ToList()).GetHtml()
}

Courier Management System/Areas/Admin/Views/Jobs/_OrdersList.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";
}

@Html.Action("OrdersListGrid", new
{
    id = ViewBag.Id
})